name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release the installable python package.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            setup.py

      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.2

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish
